Changes the PATH variable modified when installing conan package.
Xav83/chocolatey-packages pull request #8
Opened 2022-08-11 20:41 UTC by Xav83

Changes the PATH variable modified when installing conan package.

Related to #7

2022-08-12 14:06 UTC, vectorsli requested changes

2022-08-12 14:06 UTC, vectorsli commented on automatic/conan/tools/chocolateyInstall.ps1
> +Install-ChocolateyPath -PathToInstall $conan_path -PathType Process
```suggestion
Install-ChocolateyPath -PathToInstall $conan_path -PathType Machine
```
`Process` would mean only the environment of the current executing process and would mean that `conan` isn't available for anyone.

2022-09-11 16:44 UTC, vectorsli commented
I like the approach for the variable to be configurable. But please set the default value to `Machine` since that is what I'd guess most people want. The current default of `Process` doesn't do anything

2022-09-11 17:06 UTC, Xav83 commented
Actually, I am going to change it back to `User` so that the default behavior of the package won't change for the users who are already installing it. If, in the future, more people asks me to change this behavior, I will re-consider this choice :wink:

2022-09-12 06:28 UTC, vectorsli commented
Alright, thanks for the update!

2022-11-10 18:31 UTC, merged